### PR TITLE
Some new changes to prepare for Babel 6, React 14.3 and latest React Router

### PR DESCRIPTION
**Pull request by bitkidd**
There are lots of new things in all these libs. I tried to implement them, especially Babel 6 changes and its plugins, React DOM separation and React Router ES2015 syntax. 
Need help in renderTo service. I changed it a lot and it is a breaking update.

```
import React from 'react'
import { renderToString } from 'react-dom/server'
import { match, RoutingContext } from 'react-router'

module.exports = function( routes_passed, res, path, locals_passed, state_passed, layout_passed ) {

  const routes = routes_passed
  const layout = layout_passed || 'layout'
  const locals = locals_passed || { title:'', description:'' }

  match({
    routes: routes,
    location: path
  }, (error, redirectLocation, renderProps) => {

    if (error) {

      res.badRequest(error.message);

    } else if (redirectLocation) {

      res.redirect(302, redirectLocation.pathname + redirectLocation.search)

    } else if (renderProps) {

      res.render( layout, {
        locals: locals,
        body: renderToString(<RoutingContext {...renderProps} />)
      });

    } else {

      res.notFound();

    }

  });

}
```

### CODE REVIEW

**Comment by wi2** [comment]
Thanks @keeross 
Nice work..  i check that and i probably merge it..

Sorry, but i don't really understand your problem.. (my english is so poor..) , can you explain a little more .. 
So, i check your function and i don't see something wrong..  And i did a very similar  here with last version of react and react-router.. you can check here maybe can help : https://github.com/wi2/calendar-example/blob/master/api/services/resTo.js  

Mike

**Comment by bitkidd** [comment]
Yeap your version is better. Mine will break some stuff for sure.

**Comment by wi2** [comment]
@keeross 
thanks, but i don't really think my solution it's a good approach. Yes, it's just a wrapper of res.view..

I actually remove this service (resTo) and replace by res.react  
see :  
https://github.com/wi2/calendar-example/blob/master/api/responses/react.js
and a controller (usecase) : 
https://github.com/wi2/calendar-example/blob/master/api/controllers/AdminController.js

Mike

**Comment by bitkidd** [comment]
Nice! To use response for react is a great idea, seems more natural. Then we need to update a browserify task, adding watch: true, this makes builds 10x faster and uses internal watchify.
And remove react from watch, as soon as browserify will watch all the changes.

**Pull request closed without merging**
